@host = http://localhost
@port = 5237

@Restaurants.API_HostAddress = {{host}}:{{port}}
GET {{Restaurants.API_HostAddress}}/api/restaurants
###
GET {{Restaurants.API_HostAddress}}/api/restaurants/d82cf978-546f-4218-a161-08dc7170c4d6
###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: "application/json"

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54321"
}

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/c5ff49d8-8e61-4b85-3ebc-08dc736e597